[package]
name = "resolvd-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
dns = { path = "../dns" }
libresolv = { path = "../libresolv" }

[[bin]]
name = "dns_decode"
path = "fuzz_targets/dns_decode.rs"
test = false
doc = false
bench = false

[[bin]]
name = "resolv_wire"
path = "fuzz_targets/resolv_wire.rs"
test = false
doc = false
bench = false

[workspace]
