[package]
name        = "dev.peios.resolvd-debuginfo"
description = "Debugging symbols for the Peios name-resolution service"

[dependencies]
"dev.peios.resolvd" = "= {{release}}"

[files]
"@source:LICENSE"                  = "usr/share/licenses/dev.peios.resolvd-debuginfo/LICENSE"
":debug/resolvd/usr/lib/debug/**"  = "usr/lib/debug"
