[package]
name        = "dev.peios.resolvd-nss-debuginfo"
description = "Debugging symbols for the Peios NSS host-resolution module"

[dependencies]
"dev.peios.resolvd-nss" = "= {{version}}-1"

[files]
"@source:LICENSE"             = "usr/share/licenses/dev.peios.resolvd-nss-debuginfo/LICENSE"
":debug/nss/usr/lib/debug/**" = "usr/lib/debug"
